### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [koryga2012/homework_1#1]
1)
нет разделителя
![image](https://user-images.githubusercontent.com/8464662/76524623-05d3ba80-6473-11ea-92fd-12eeb452900b.png)

2)
толщина бордеров не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/76524667-1a17b780-6473-11ea-9619-52a73be3bb69.png)

3)
![image](https://user-images.githubusercontent.com/8464662/76524711-30257800-6473-11ea-801c-4b10daa0907e.png)

**Comment by koryga2012** [comment]
Вроде бы все исправил

**Comment by Alecto** [comment]
ссылки?

чт, 12 бер. 2020 о 22:19 koryga2012 <notifications@github.com> пише:

**Comment by koryga2012** [comment]
https://github.com/koryga2012/homework-1.io.git - репозиторий
https://koryga2012.github.io/homework-1.io/ - результат

**Comment by Alecto** [comment]
отлично, работа принята.
работа чья?

в журнале не находится ))
[image: image.png]

пт, 13 бер. 2020 о 14:57 koryga2012 <notifications@github.com> пише:

**Comment by koryga2012** [comment]
Олейник Вячеслав)
